//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ExpressPcArızaTakip.Models.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Problem
    {
        public int Id { get; set; }
        public int ProblemUserId { get; set; }
        public int ProblemReasonId { get; set; }
        public int ProblemSituationId { get; set; }
        public string ProblemDetails { get; set; }
        public Nullable<int> ProblemDevicePartId { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public Nullable<byte> Status { get; set; }
        public string Description { get; set; }
        public Nullable<int> ProblemCompanyId { get; set; }
        public Nullable<int> ProblemDeviceId { get; set; }
    
        public virtual Company Company { get; set; }
        public virtual Device Device { get; set; }
        public virtual DevicePart DevicePart { get; set; }
        public virtual Reason Reason { get; set; }
        public virtual Situation Situation { get; set; }
        public virtual User User { get; set; }
    }
}
